apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm
  namespace: nexus-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tm
  template:
    metadata:
      labels:
        app: tm
    spec:
      containers:
        - name: tm
          image: 192.68.100.5:8443/timesheet:3.1.2-185
          ports:
           - containerPort: 8085
      imagePullSecrets:
        - name: my-nexus-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tm
  namespace: nexus-namespace
spec:
  clusterIP: 10.152.183.167
  selector:
    app: tm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP




